# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""Rollout status reporter for the Code Intelligence Review Bot.

Generates PR summary and nightly audit reports showing current rollout
phase, readiness signals, and finding trends.

OMN-2500: Implement OBSERVE -> WARN -> BLOCK rollout progression.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from omniintelligence.review_bot.rollout.evaluator_rollout_readiness import (
    RolloutReadinessReport,
)
from omniintelligence.review_bot.rollout.model_enforcement_mode import EnforcementMode


@dataclass
class RolloutStatusReport:
    """Status report for inclusion in PR summaries.

    Attributes:
        current_mode: Active enforcement mode.
        finding_summary: Summary of findings by severity.
        readiness_report: Advisory graduation readiness (may be None).
        markdown_body: Pre-rendered markdown for PR comment/issue body.
    """

    current_mode: EnforcementMode
    finding_summary: dict[str, int] = field(default_factory=dict)
    readiness_report: RolloutReadinessReport | None = None
    markdown_body: str = ""


class ReporterRolloutStatus:
    """Generates rollout status reports for PR summaries and nightly audits.

    Usage::

        reporter = ReporterRolloutStatus()
        report = reporter.build_pr_summary(
            mode=EnforcementMode.WARN,
            finding_summary={"BLOCKER": 0, "WARNING": 3, "INFO": 12},
            readiness_report=readiness_report,
        )
        print(report.markdown_body)
    """

    def build_pr_summary(
        self,
        mode: EnforcementMode,
        finding_summary: dict[str, int],
        readiness_report: RolloutReadinessReport | None = None,
    ) -> RolloutStatusReport:
        """Build a PR comment summary of the current rollout state.

        Args:
            mode: Current enforcement mode.
            finding_summary: Finding counts by severity key.
            readiness_report: Optional advisory graduation readiness.

        Returns:
            RolloutStatusReport with rendered markdown body.
        """
        lines = [
            "## Code Intelligence Review Bot",
            "",
            f"**Mode**: `{mode.value}` -- {self._mode_description(mode)}",
            "",
        ]

        # Finding summary
        lines += self._render_finding_summary(finding_summary, mode)

        # Readiness signals (advisory only)
        if readiness_report is not None:
            lines += self._render_readiness(readiness_report)

        lines.append("")
        lines.append(
            "_This report is generated by the Code Intelligence Review Bot. "
            "Enforcement mode changes require manual update to policy YAML._"
        )

        markdown = "\n".join(lines)
        return RolloutStatusReport(
            current_mode=mode,
            finding_summary=finding_summary,
            readiness_report=readiness_report,
            markdown_body=markdown,
        )

    def build_nightly_audit_report(
        self,
        mode: EnforcementMode,
        finding_summary: dict[str, int],
        trend_vs_7d: dict[str, int],
        top_rules: list[tuple[str, int]],
    ) -> RolloutStatusReport:
        """Build a nightly audit report for posting as a GitHub issue.

        The nightly audit runs in any enforcement mode and posts as an
        issue (not a PR comment).

        Args:
            mode: Current enforcement mode.
            finding_summary: Finding counts by severity.
            trend_vs_7d: Delta vs 7 days ago (positive = more findings).
            top_rules: List of (rule_id, count) tuples sorted by count.

        Returns:
            RolloutStatusReport with rendered nightly audit markdown.
        """
        lines = [
            "## Code Intelligence Review Bot - Nightly Audit",
            "",
            f"**Enforcement Mode**: `{mode.value}`",
            "",
            "### Finding Summary",
            "",
        ]

        for severity, count in sorted(finding_summary.items()):
            trend_val = trend_vs_7d.get(severity, 0)
            trend_str = self._format_trend(trend_val)
            lines.append(f"- **{severity}**: {count} {trend_str}")

        lines += [
            "",
            "### Top 5 Rules by Finding Count",
            "",
        ]

        for i, (rule_id, count) in enumerate(top_rules[:5], 1):
            lines.append(f"{i}. `{rule_id}`: {count} finding(s)")

        lines += [
            "",
            "_Nightly audit runs regardless of enforcement mode. "
            "This report is informational._",
        ]

        markdown = "\n".join(lines)
        return RolloutStatusReport(
            current_mode=mode,
            finding_summary=finding_summary,
            markdown_body=markdown,
        )

    def _mode_description(self, mode: EnforcementMode) -> str:
        descriptions = {
            EnforcementMode.OBSERVE: "Silent mode; findings recorded but CI always passes",
            EnforcementMode.WARN: "Visible mode; findings posted as comments; CI always passes",
            EnforcementMode.BLOCK: "Gate mode; BLOCKER findings fail CI",
        }
        return descriptions[mode]

    def _render_finding_summary(
        self,
        finding_summary: dict[str, int],
        mode: EnforcementMode,
    ) -> list[str]:
        if not finding_summary:
            return ["No findings.", ""]

        lines = ["### Findings", ""]
        for severity in ("BLOCKER", "WARNING", "INFO"):
            count = finding_summary.get(severity, 0)
            if count > 0:
                blocking_note = ""
                if severity == "BLOCKER" and mode.blocks_on_blocker:
                    blocking_note = " (CI blocked)"
                lines.append(f"- **{severity}**: {count}{blocking_note}")

        lines.append("")
        return lines

    def _render_readiness(self, report: RolloutReadinessReport) -> list[str]:
        lines = [
            f"### Graduation Readiness: {report.current_mode.value} -> {report.target_mode.value}",
            "",
            "_Advisory only. Progression requires manual policy YAML update._",
            "",
        ]

        for signal in report.signals:
            icon = "+" if signal.is_ready else "-"
            lines.append(f"- [{icon}] {signal.description}")
            if signal.detail:
                lines.append(f"  - {signal.detail}")

        overall = "Ready" if report.overall_ready else "Not ready"
        lines.append(
            f"\n**Overall**: {overall} ({report.ready_count}/{report.total_count} signals)"
        )
        lines.append("")
        return lines

    def _format_trend(self, delta: int) -> str:
        if delta > 0:
            return f"(+{delta} vs 7d ago)"
        if delta < 0:
            return f"({delta} vs 7d ago)"
        return "(no change vs 7d ago)"


__all__ = ["ReporterRolloutStatus", "RolloutStatusReport"]
