# =============================================================================
# Cross-Repo Validation Policy - Kafka Import Guard
# =============================================================================
#
# Purpose: Prevent direct Kafka library imports in ONEX node code.
# Nodes must use ProtocolKafkaPublisher abstractions, not raw Kafka clients.
#
# Reference: ARCH-002 "Runtime owns all Kafka plumbing"
# Ticket: OMN-1749
# =============================================================================

---
policy_id: omniintelligence_kafka_guard
policy_version:
  major: 1
  minor: 0
  patch: 0
repo_id: omniintelligence

# =============================================================================
# Discovery - What files to scan
# =============================================================================
discovery:
  include_globs:
    - "src/omniintelligence/nodes/**/*.py"
  exclude_globs:
    - "**/__pycache__/**"
    - "**/node_tests/**"
    - "**/__init__.py"
  language_mode: python
  skip_generated: true
  generated_markers:
    - "# AUTO-GENERATED"
    - "# DO NOT EDIT"

# =============================================================================
# Rules
# =============================================================================
rules:
  forbidden_imports:
    enabled: true
    severity: error
    # Block entire Kafka libraries, not just consumer classes.
    # This prevents bypassing via aliases or alternate import paths.
    forbidden_prefixes:
      - "aiokafka"
      - "confluent_kafka"
      - "kafka"
    forbidden_modules: []
    exceptions: []

# =============================================================================
# Baselines
# =============================================================================
# No baseline needed - nodes directory is clean (verified 2026-02-01)
baselines: []
