"""Output field model for canary impure tool."""

from typing import Optional

from pydantic import BaseModel, Field


class ModelOutputField(BaseModel):
    """Model for dynamic output field data."""

    field_type: str = Field(description="Type of the output field")
    field_name: str = Field(description="Name of the output field")
    field_value: Optional[str] = Field(
        default=None, description="String representation of the field value"
    )
    metadata: Optional[str] = Field(
        default=None, description="Additional metadata about the field"
    )
    validation_status: str = Field(
        default="valid", description="Validation status of the field"
    )

    class Config:
        json_schema_extra = {
            "examples": [
                {
                    "field_type": "computed_result",
                    "field_name": "processing_output",
                    "field_value": "Operation completed successfully",
                    "metadata": "Generated by canary impure tool",
                    "validation_status": "valid",
                }
            ]
        }
