# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""Deterministic, backend-neutral code projection seam."""

from omniintelligence.code_projection.codec import (
    build_code_projection_batch,
    decode_canonical_batch,
    derive_code_source_id,
    encode_canonical_batch,
    make_code_chunk,
    make_code_edge,
    make_code_node,
    make_code_source,
    parse_code_projection_batch,
    plan_code_projection_replay,
    serialize_code_projection_batch,
)
from omniintelligence.code_projection.models import (
    CODE_PROJECTION_IDENTITY_VERSION,
    CODE_PROJECTION_MANIFEST_VERSION,
    CODE_PROJECTION_NAME,
    CODE_PROJECTION_REDUCER_VERSION,
    CODE_PROJECTION_SCHEMA_ID,
    CODE_PROJECTION_SCHEMA_VERSION,
    CODE_PROJECTION_VERSION,
    ModelCodeProjectionBatch,
    ModelCodeProjectionCursor,
    ModelCodeProjectionDocument,
    ModelCodeProjectionEdge,
    ModelCodeProjectionLabel,
    ModelCodeProjectionNode,
    ModelCodeProjectionPolicy,
    ModelCodeProjectionProvenance,
    ModelCodeProjectionReplayManifest,
    ModelCodeProjectionReplayPlan,
    ModelCodeProjectionSource,
    ModelCodeProjectionSpan,
)

__all__ = [
    "CODE_PROJECTION_IDENTITY_VERSION",
    "CODE_PROJECTION_MANIFEST_VERSION",
    "CODE_PROJECTION_NAME",
    "CODE_PROJECTION_REDUCER_VERSION",
    "CODE_PROJECTION_SCHEMA_ID",
    "CODE_PROJECTION_SCHEMA_VERSION",
    "CODE_PROJECTION_VERSION",
    "ModelCodeProjectionBatch",
    "ModelCodeProjectionCursor",
    "ModelCodeProjectionDocument",
    "ModelCodeProjectionEdge",
    "ModelCodeProjectionLabel",
    "ModelCodeProjectionNode",
    "ModelCodeProjectionPolicy",
    "ModelCodeProjectionProvenance",
    "ModelCodeProjectionReplayManifest",
    "ModelCodeProjectionReplayPlan",
    "ModelCodeProjectionSource",
    "ModelCodeProjectionSpan",
    "build_code_projection_batch",
    "decode_canonical_batch",
    "derive_code_source_id",
    "encode_canonical_batch",
    "make_code_chunk",
    "make_code_edge",
    "make_code_node",
    "make_code_source",
    "parse_code_projection_batch",
    "plan_code_projection_replay",
    "serialize_code_projection_batch",
]
