# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""FROZEN canonical handler-shape ratchet baseline — OMN-14355.

Generated by ``scripts/ci/canonical_handler_shape.py --update``. Do not edit by hand.

``NON_CANONICAL`` is the frozen set of nodes whose contract-declared handler is not
the canonical typed-payload shape (definition B). It is monotonically
NON-INCREASING: it may only shrink. A node leaves this set (flips canonical) ONLY
with a committed adequacy receipt under ``scripts/ci/adequacy_receipts/`` — a shape
flip alone is not proof of equivalence (the OMN-14208 trap). A NEW non-canonical
node, or growth of this set, HARD-FAILS CI + pre-commit. Retirement mechanism = the
RSD canonical rewrite regenerating these handlers, each with an adequacy receipt.
"""

NON_CANONICAL: tuple[str, ...] = (
    "omniintelligence.nodes.audit",
    "omniintelligence.nodes.node_agent_behavior_eval_compute",
    "omniintelligence.nodes.node_anti_gaming_alerter_effect",
    "omniintelligence.nodes.node_anti_gaming_guardrails_compute",
    "omniintelligence.nodes.node_ast_extraction_compute",
    "omniintelligence.nodes.node_behavior_scenario_generator_compute",
    "omniintelligence.nodes.node_bloom_eval_orchestrator",
    "omniintelligence.nodes.node_chunk_classifier_compute",
    "omniintelligence.nodes.node_ci_error_classifier_compute",
    "omniintelligence.nodes.node_ci_failure_tracker_effect",
    "omniintelligence.nodes.node_ci_fingerprint_compute",
    "omniintelligence.nodes.node_code_crawler_effect",
    "omniintelligence.nodes.node_code_entity_bridge_compute",
    "omniintelligence.nodes.node_compliance_evaluate_effect",
    "omniintelligence.nodes.node_context_item_writer_effect",
    "omniintelligence.nodes.node_contract_eval_compute",
    "omniintelligence.nodes.node_crawl_scheduler_effect",
    "omniintelligence.nodes.node_debug_fix_record_effect",
    "omniintelligence.nodes.node_debug_retrieval_compute",
    "omniintelligence.nodes.node_dispatch_outcome_eval_effect",
    "omniintelligence.nodes.node_doc_promotion_reducer",
    "omniintelligence.nodes.node_doc_retrieval_compute",
    "omniintelligence.nodes.node_doc_staleness_detector_effect",
    "omniintelligence.nodes.node_document_fetch_effect",
    "omniintelligence.nodes.node_document_parser_compute",
    "omniintelligence.nodes.node_embedding_generation_effect",
    "omniintelligence.nodes.node_enforcement_feedback_effect",
    "omniintelligence.nodes.node_evidence_collection_effect",
    "omniintelligence.nodes.node_execution_trace_parser_compute",
    "omniintelligence.nodes.node_git_repo_crawler_effect",
    "omniintelligence.nodes.node_gmail_intent_evaluator_effect",
    "omniintelligence.nodes.node_intelligence_orchestrator",
    "omniintelligence.nodes.node_intelligence_reducer",
    "omniintelligence.nodes.node_intent_classifier_compute",
    "omniintelligence.nodes.node_intent_cost_forecast_compute",
    "omniintelligence.nodes.node_intent_drift_detect_compute",
    "omniintelligence.nodes.node_intent_graph_reducer",
    "omniintelligence.nodes.node_linear_crawler_effect",
    "omniintelligence.nodes.node_llm_routing_decision_effect",
    "omniintelligence.nodes.node_memory_eval_compute",
    "omniintelligence.nodes.node_navigation_retriever_effect",
    "omniintelligence.nodes.node_objective_ab_framework_compute",
    "omniintelligence.nodes.node_pattern_assembler_orchestrator",
    "omniintelligence.nodes.node_pattern_compliance_effect",
    "omniintelligence.nodes.node_pattern_demotion_effect",
    "omniintelligence.nodes.node_pattern_extraction_compute",
    "omniintelligence.nodes.node_pattern_feedback_effect",
    "omniintelligence.nodes.node_pattern_learning_compute",
    "omniintelligence.nodes.node_pattern_learning_effect",
    "omniintelligence.nodes.node_pattern_lifecycle_effect",
    "omniintelligence.nodes.node_pattern_matching_compute",
    "omniintelligence.nodes.node_pattern_projection_effect",
    "omniintelligence.nodes.node_pattern_promotion_effect",
    "omniintelligence.nodes.node_pattern_storage_effect",
    "omniintelligence.nodes.node_plan_reviewer_multi_compute",
    "omniintelligence.nodes.node_policy_state_reducer",
    "omniintelligence.nodes.node_protocol_handler_effect",
    "omniintelligence.nodes.node_quality_scoring_compute",
    "omniintelligence.nodes.node_routing_feedback_effect",
    "omniintelligence.nodes.node_scoring_reducer_compute",
    "omniintelligence.nodes.node_semantic_analysis_compute",
    "omniintelligence.nodes.node_storage_router_effect",
    "omniintelligence.nodes.node_success_criteria_matcher_compute",
    "omniintelligence.nodes.node_tcb_generation_compute",
    "omniintelligence.nodes.node_watchdog_effect",
)
