name: management_subcontract
version:
  major: 1
  minor: 0
  patch: 0

description: |
  Management operations subcontract for intelligence reducer.
  Handles FSM lifecycle, lease management, and administrative operations.

operations:
  list_entities:
    description: List entities in a given FSM state
    input:
      fsm_type: EnumFSMType
      state: str
      limit: int
      offset: int
    output:
      entities: list[dict]
      total_count: int

  get_fsm_statistics:
    description: Get statistics for an FSM type
    input:
      fsm_type: EnumFSMType
      time_range_seconds: int
    output:
      total_entities: int
      state_distribution: dict
      average_transition_time_seconds: float
      transitions_per_hour: float

  acquire_lease:
    description: Acquire action lease for distributed coordination
    input:
      fsm_type: EnumFSMType
      entity_id: str
      lease_duration_seconds: int
      requester_id: str
    output:
      success: bool
      lease_id: str
      epoch: int
      expires_at: str

  release_lease:
    description: Release action lease
    input:
      lease_id: str
      epoch: int
    output:
      success: bool
      released: bool

  renew_lease:
    description: Renew an existing lease
    input:
      lease_id: str
      epoch: int
      extend_seconds: int
    output:
      success: bool
      new_expires_at: str

  cleanup_expired_leases:
    description: Clean up expired action leases
    input:
      batch_size: int
    output:
      cleaned_count: int

  get_entity_history:
    description: Get state transition history for an entity
    input:
      fsm_type: EnumFSMType
      entity_id: str
      limit: int
    output:
      transitions: list[dict]
      total_count: int

  force_transition:
    description: Force a state transition (admin operation)
    input:
      fsm_type: EnumFSMType
      entity_id: str
      target_state: str
      reason: str
      admin_user: str
    output:
      success: bool
      previous_state: str
      current_state: str

  delete_entity:
    description: Delete an entity from FSM tracking
    input:
      fsm_type: EnumFSMType
      entity_id: str
      reason: str
    output:
      success: bool
      deleted: bool

# Lease management policies
lease_policies:
  default_duration_seconds: 300
  max_duration_seconds: 3600
  renewal_window_seconds: 60
  cleanup_interval_seconds: 300

  auto_cleanup:
    enabled: true
    batch_size: 100
    run_interval_seconds: 300

# Entity lifecycle policies
lifecycle_policies:
  retention:
    completed_entities_ttl_hours: 720  # 30 days
    failed_entities_ttl_hours: 2160    # 90 days
    abandoned_entities_ttl_hours: 168  # 7 days

  archival:
    enabled: true
    archive_after_hours: 720
    archive_table: fsm_state_archive

  cleanup:
    enabled: true
    run_interval_hours: 24
    batch_size: 1000

# Authorization
authorization:
  operations:
    list_entities: ["read"]
    get_fsm_statistics: ["read"]
    acquire_lease: ["write"]
    release_lease: ["write"]
    renew_lease: ["write"]
    cleanup_expired_leases: ["admin"]
    get_entity_history: ["read"]
    force_transition: ["admin"]
    delete_entity: ["admin"]
